// MASTER KOTOBA: Hiragana Lengkap (Indonesia = Bacaan/Karakter, Romaji = Hiragana Asli)
const MASTER_HIRAGANA_LENGKAP = {
  submenus: [
    { id: 'hiragana', title: 'Hiragana' },
    { id: 'katakana', title: 'Katakana' },
    { id: 'kata_bilangan', title: 'Kata Bilangan' },
    { id: 'ungkapan_waktu', title: 'Ungkapan Waktu' },
    { id: 'penanda_waktu', title: 'Penanda Waktu' },
    { id: 'aisatsu', title: 'Salam' },
    { id: 'kazoku', title: 'Keluarga' },
    { id: 'kata_benda', title: 'Kata Benda' },
    { id: 'kata_kerja_gol1', title: 'Kata Kerja Gol. 1' },
    { id: 'kata_kerja_gol2', title: 'Kata Kerja Gol. 2' },
    { id: 'kata_kerja_gol3', title: 'Kata Kerja Gol. 3' }
  ],
  vocabData: {
    "hiragana": [
      { indonesia: "a", romaji: "あ" },
      { indonesia: "i", romaji: "い" },
      { indonesia: "u", romaji: "う" },
      { indonesia: "e", romaji: "え" },
      { indonesia: "o", romaji: "お" },
      { indonesia: "ka", romaji: "か" },
      { indonesia: "ki", romaji: "き" },
      { indonesia: "ku", romaji: "く" },
      { indonesia: "ke", romaji: "け" },
      { indonesia: "ko", romaji: "こ" },
      { indonesia: "sa", romaji: "さ" },
      { indonesia: "shi", romaji: "し" },
      { indonesia: "su", romaji: "す" },
      { indonesia: "se", romaji: "せ" },
      { indonesia: "so", romaji: "そ" },
      { indonesia: "ta", romaji: "た" },
      { indonesia: "chi", romaji: "ち" },
      { indonesia: "tsu", romaji: "つ" },
      { indonesia: "te", romaji: "て" },
      { indonesia: "to", romaji: "と" },
      { indonesia: "na", romaji: "な" },
      { indonesia: "ni", romaji: "に" },
      { indonesia: "nu", romaji: "ぬ" },
      { indonesia: "ne", romaji: "ね" },
      { indonesia: "no", romaji: "の" },
      { indonesia: "ha", romaji: "は" },
      { indonesia: "hi", romaji: "ひ" },
      { indonesia: "fu", romaji: "ふ" },
      { indonesia: "he", romaji: "へ" },
      { indonesia: "ho", romaji: "ほ" },
      { indonesia: "ma", romaji: "ま" },
      { indonesia: "mi", romaji: "み" },
      { indonesia: "mu", romaji: "む" },
      { indonesia: "me", romaji: "め" },
      { indonesia: "mo", romaji: "も" },
      { indonesia: "ya", romaji: "や" },
      { indonesia: "yu", romaji: "ゆ" },
      { indonesia: "yo", romaji: "よ" },
      { indonesia: "ra", romaji: "ら" },
      { indonesia: "ri", romaji: "り" },
      { indonesia: "ru", romaji: "る" },
      { indonesia: "re", romaji: "れ" },
      { indonesia: "ro", romaji: "ろ" },
      { indonesia: "wa", romaji: "わ" },
      { indonesia: "wo", romaji: "を" },
      { indonesia: "n", romaji: "ん" },
      { indonesia: "ga", romaji: "が" },
      { indonesia: "gi", romaji: "ぎ" },
      { indonesia: "gu", romaji: "ぐ" },
      { indonesia: "ge", romaji: "げ" },
      { indonesia: "go", romaji: "ご" },
      { indonesia: "za", romaji: "ざ" },
      { indonesia: "ji", romaji: "じ" },
      { indonesia: "zu", romaji: "ず" },
      { indonesia: "ze", romaji: "ぜ" },
      { indonesia: "zo", romaji: "ぞ" },
      { indonesia: "da", romaji: "だ" },
      { indonesia: "dji", romaji: "ぢ" },
      { indonesia: "dzu", romaji: "づ" },
      { indonesia: "de", romaji: "で" },
      { indonesia: "do", romaji: "ど" },
      { indonesia: "ba", romaji: "ば" },
      { indonesia: "bi", romaji: "び" },
      { indonesia: "bu", romaji: "ぶ" },
      { indonesia: "be", romaji: "べ" },
      { indonesia: "bo", romaji: "ぼ" },
      { indonesia: "pa", romaji: "ぱ" },
      { indonesia: "pi", romaji: "ぴ" },
      { indonesia: "pu", romaji: "ぷ" },
      { indonesia: "pe", romaji: "ぺ" },
      { indonesia: "po", romaji: "ぽ" },
      { indonesia: "kya", romaji: "きゃ" },
      { indonesia: "kyu", romaji: "きゅ" },
      { indonesia: "kyo", romaji: "きょ" },
      { indonesia: "sha", romaji: "しゃ" },
      { indonesia: "shu", romaji: "しゅ" },
      { indonesia: "sho", romaji: "しょ" },
      { indonesia: "cha", romaji: "ちゃ" },
      { indonesia: "chu", romaji: "ちゅ" },
      { indonesia: "cho", romaji: "ちょ" },
      { indonesia: "nya", romaji: "にゃ" },
      { indonesia: "nyu", romaji: "にゅ" },
      { indonesia: "nyo", romaji: "にょ" },
      { indonesia: "hya", romaji: "ひゃ" },
      { indonesia: "hyu", romaji: "ひゅ" },
      { indonesia: "hyo", romaji: "ひょ" },
      { indonesia: "mya", romaji: "みゃ" },
      { indonesia: "myu", romaji: "みゅ" },
      { indonesia: "myo", romaji: "みょ" },
      { indonesia: "rya", romaji: "りゃ" },
      { indonesia: "ryu", romaji: "りゅ" },
      { indonesia: "ryo", romaji: "りょ" },
      { indonesia: "gya", romaji: "ぎゃ" },
      { indonesia: "gyu", romaji: "ぎゅ" },
      { indonesia: "gyo", romaji: "ぎょ" },
      { indonesia: "ja", romaji: "じゃ" },
      { indonesia: "ju", romaji: "じゅ" },
      { indonesia: "jo", romaji: "じょ" },
      { indonesia: "bya", romaji: "びゃ" },
      { indonesia: "byu", romaji: "びゅ" },
      { indonesia: "byo", romaji: "びょ" },
      { indonesia: "pya", romaji: "ぴゃ" },
      { indonesia: "pyu", romaji: "ぴゅ" },
      { indonesia: "pyo", romaji: "ぴょ" }
    ],
    "katakana": [
      { indonesia: "a", romaji: "ア" },
      { indonesia: "i", romaji: "イ" },
      { indonesia: "u", romaji: "ウ" },
      { indonesia: "e", romaji: "エ" },
      { indonesia: "o", romaji: "オ" },
      { indonesia: "ka", romaji: "カ" },
      { indonesia: "ki", romaji: "キ" },
      { indonesia: "ku", romaji: "ク" },
      { indonesia: "ke", romaji: "ケ" },
      { indonesia: "ko", romaji: "コ" },
      { indonesia: "sa", romaji: "サ" },
      { indonesia: "shi", romaji: "シ" },
      { indonesia: "su", romaji: "ス" },
      { indonesia: "se", romaji: "セ" },
      { indonesia: "so", romaji: "ソ" },
      { indonesia: "ta", romaji: "タ" },
      { indonesia: "chi", romaji: "チ" },
      { indonesia: "tsu", romaji: "ツ" },
      { indonesia: "te", romaji: "テ" },
      { indonesia: "to", romaji: "ト" },
      { indonesia: "na", romaji: "ナ" },
      { indonesia: "ni", romaji: "ニ" },
      { indonesia: "nu", romaji: "ヌ" },
      { indonesia: "ne", romaji: "ネ" },
      { indonesia: "no", romaji: "ノ" },
      { indonesia: "ha", romaji: "ハ" },
      { indonesia: "hi", romaji: "ヒ" },
      { indonesia: "fu", romaji: "フ" },
      { indonesia: "he", romaji: "ヘ" },
      { indonesia: "ho", romaji: "ホ" },
      { indonesia: "ma", romaji: "マ" },
      { indonesia: "mi", romaji: "ミ" },
      { indonesia: "mu", romaji: "ム" },
      { indonesia: "me", romaji: "メ" },
      { indonesia: "mo", romaji: "モ" },
      { indonesia: "ya", romaji: "ヤ" },
      { indonesia: "yu", romaji: "ユ" },
      { indonesia: "yo", romaji: "ヨ" },
      { indonesia: "ra", romaji: "ラ" },
      { indonesia: "ri", romaji: "リ" },
      { indonesia: "ru", romaji: "ル" },
      { indonesia: "re", romaji: "レ" },
      { indonesia: "ro", romaji: "ロ" },
      { indonesia: "wa", romaji: "ワ" },
      { indonesia: "wo", romaji: "ヲ" },
      { indonesia: "n", romaji: "ン" },
      { indonesia: "ga", romaji: "ガ" },
      { indonesia: "gi", romaji: "ギ" },
      { indonesia: "gu", romaji: "グ" },
      { indonesia: "ge", romaji: "ゲ" },
      { indonesia: "go", romaji: "ゴ" },
      { indonesia: "za", romaji: "ザ" },
      { indonesia: "ji", romaji: "ジ" },
      { indonesia: "zu", romaji: "ズ" },
      { indonesia: "ze", romaji: "ゼ" },
      { indonesia: "zo", romaji: "ゾ" },
      { indonesia: "da", romaji: "ダ" },
      { indonesia: "dji", romaji: "ヂ" },
      { indonesia: "dzu", romaji: "ヅ" },
      { indonesia: "de", romaji: "デ" },
      { indonesia: "do", romaji: "ド" },
      { indonesia: "ba", romaji: "バ" },
      { indonesia: "bi", romaji: "ビ" },
      { indonesia: "bu", romaji: "ブ" },
      { indonesia: "be", romaji: "ベ" },
      { indonesia: "bo", romaji: "ボ" },
      { indonesia: "pa", romaji: "パ" },
      { indonesia: "pi", romaji: "ピ" },
      { indonesia: "pu", romaji: "プ" },
      { indonesia: "pe", romaji: "ペ" },
      { indonesia: "po", romaji: "ポ" },
      { indonesia: "kya", romaji: "キャ" },
      { indonesia: "kyu", romaji: "キュ" },
      { indonesia: "kyo", romaji: "キョ" },
      { indonesia: "sha", romaji: "シャ" },
      { indonesia: "shu", romaji: "シュ" },
      { indonesia: "sho", romaji: "ショ" },
      { indonesia: "cha", romaji: "チャ" },
      { indonesia: "chu", romaji: "チュ" },
      { indonesia: "cho", romaji: "チョ" },
      { indonesia: "nya", romaji: "ニャ" },
      { indonesia: "nyu", romaji: "ニュ" },
      { indonesia: "nyo", romaji: "ニョ" },
      { indonesia: "hya", romaji: "ヒャ" },
      { indonesia: "hyu", romaji: "ヒュ" },
      { indonesia: "hyo", romaji: "ヒョ" },
      { indonesia: "mya", romaji: "ミャ" },
      { indonesia: "myu", romaji: "ミュ" },
      { indonesia: "myo", romaji: "ミョ" },
      { indonesia: "rya", romaji: "リャ" },
      { indonesia: "ryu", romaji: "リュ" },
      { indonesia: "ryo", romaji: "リョ" },
      { indonesia: "gya", romaji: "ギャ" },
      { indonesia: "gyu", romaji: "ギュ" },
      { indonesia: "gyo", romaji: "ギョ" },
      { indonesia: "ja", romaji: "ジャ" },
      { indonesia: "ju", romaji: "ジュ" },
      { indonesia: "jo", romaji: "ジョ" },
      { indonesia: "bya", romaji: "ビャ" },
      { indonesia: "byu", romaji: "ビュ" },
      { indonesia: "byo", romaji: "ビョ" },
      { indonesia: "pya", romaji: "ピャ" },
      { indonesia: "pyu", romaji: "ピュ" },
      { indonesia: "pyo", romaji: "ピョ" },
      { indonesia: "wi", romaji: "ウィ" },
      { indonesia: "we", romaji: "ウェ" },
      { indonesia: "wo", romaji: "ウォ" },
      { indonesia: "va", romaji: "ヴァ" },
      { indonesia: "vi", romaji: "ヴィ" },
      { indonesia: "ve", romaji: "ヴェ" },
      { indonesia: "vo", romaji: "ヴォ" },
      { indonesia: "fa", romaji: "ファ" },
      { indonesia: "fi", romaji: "フィ" },
      { indonesia: "fe", romaji: "フェ" },
      { indonesia: "fo", romaji: "フォ" },
      { indonesia: "che", romaji: "チェ" },
      { indonesia: "she", romaji: "シェ" },
      { indonesia: "je", romaji: "ジェ" },
      { indonesia: "tsa", romaji: "ツァ" },
      { indonesia: "tse", romaji: "ツェ" },
      { indonesia: "tso", romaji: "ツォ" },
      { indonesia: "ti", romaji: "ティ" },
      { indonesia: "tu", romaji: "トゥ" },
      { indonesia: "di", romaji: "ディ" },
      { indonesia: "du", romaji: "ドゥ" },
      { indonesia: "dyu", romaji: "デュ" }
    ],
    "angka_bilangan": [
      { indonesia: "0 (Nol)", romaji: "zero / rei" },
      { indonesia: "1 (Satu)", romaji: "ichi" },
      { indonesia: "2 (Dua)", romaji: "ni" },
      { indonesia: "3 (Tiga)", romaji: "san" },
      { indonesia: "4 (Empat)", romaji: "yon / shi" },
      { indonesia: "5 (Lima)", romaji: "go" },
      { indonesia: "6 (Enam)", romaji: "roku" },
      { indonesia: "7 (Tujuh)", romaji: "nana / shichi" },
      { indonesia: "8 (Delapan)", romaji: "hachi" },
      { indonesia: "9 (Sembilan)", romaji: "kyuu / ku" },
      { indonesia: "10 (Sepuluh)", romaji: "juu" },
      { indonesia: "11 (Sebelas)", romaji: "juu ichi" },
      { indonesia: "12 (Dua belas)", romaji: "juu ni" },
      { indonesia: "13 (Tiga belas)", romaji: "juu san" },
      { indonesia: "14 (Empat belas)", romaji: "juu yon / juu shi" },
      { indonesia: "15 (Lima belas)", romaji: "juu go" },
      { indonesia: "20 (Dua puluh)", romaji: "ni juu" },
      { indonesia: "30 (Tiga puluh)", romaji: "san juu" },
      { indonesia: "100 (Seratus)", romaji: "hyaku" },
      { indonesia: "300 (Tiga ratus)", romaji: "sanbyaku" },
      { indonesia: "600 (Enam ratus)", romaji: "roppyaku" },
      { indonesia: "800 (Delapan ratus)", romaji: "happyaku" },
      { indonesia: "1.000 (Seribu)", romaji: "sen" },
      { indonesia: "3.000 (Tiga ribu)", romaji: "sanzen" },
      { indonesia: "8.000 (Delapan ribu)", romaji: "hassen" },
      { indonesia: "10.000 (Puluh ribu / 1 Man)", romaji: "ichiman" },
      { indonesia: "50.000 (Lima puluh ribu / 5 Man)", romaji: "goman" },
      { indonesia: "100.000 (Seratus ribu / 10 Man)", romaji: "juuman" },
      { indonesia: "1.000.000 (Satu juta / 100 Man)", romaji: "hyakuman" },
      { indonesia: "100.000.000 (Ratus juta / 1 Oku)", romaji: "ichioku" },
      { indonesia: "17.5 (Tujuh belas koma lima)", romaji: "juunana ten go" },
      { indonesia: "1/2 (Setengah)", romaji: "ni bun no ichi" },
      { indonesia: "3/4 (Tiga per empat)", romaji: "yon bun no san" }
    ],
    
    "ungkapan_waktu": [
      // Keterangan Waktu (Hari)
      { indonesia: "Kemarin lusa", romaji: "ototoi" },
      { indonesia: "Kemarin", romaji: "kinou" },
      { indonesia: "Hari ini", romaji: "kyou" },
      { indonesia: "Besok", romaji: "ashita" },
      { indonesia: "Lusa", romaji: "asatte" },
      { indonesia: "Setiap hari", romaji: "mainichi" },

      // Pagi (朝)
      { indonesia: "Kemarin lusa pagi", romaji: "ototoi no asa" },
      { indonesia: "Kemarin pagi", romaji: "kinou no asa" },
      { indonesia: "Tadi pagi", romaji: "kesa" },
      { indonesia: "Besok pagi", romaji: "ashita no asa" },
      { indonesia: "Lusa pagi", romaji: "asatte no asa" },
      { indonesia: "Setiap pagi", romaji: "maiasa" },

      // Malam (晩 / 夜)
      { indonesia: "Kemarin lusa malam", romaji: "ototoi no ban" },
      { indonesia: "Kemarin malam", romaji: "kinou no ban" },
      { indonesia: "Malam ini", romaji: "konban" },
      { indonesia: "Besok malam", romaji: "ashita no ban" },
      { indonesia: "Lusa malam", romaji: "asatte no ban" },
      { indonesia: "Setiap malam", romaji: "maiban" },

      // Minggu (週)
      { indonesia: "Dua minggu lalu", romaji: "sen sen shuu" },
      { indonesia: "Minggu lalu", romaji: "sen shuu" },
      { indonesia: "Minggu ini", romaji: "kon shuu" },
      { indonesia: "Minggu depan", romaji: "rai shuu" },
      { indonesia: "Dua minggu lagi", romaji: "sa rai shuu" },
      { indonesia: "Setiap minggu", romaji: "maishuu" },

      // Bulan (月)
      { indonesia: "Dua bulan lalu", romaji: "sen sen getsu" },
      { indonesia: "Bulan lalu", romaji: "sen getsu" },
      { indonesia: "Bulan ini", romaji: "kon getsu" },
      { indonesia: "Bulan depan", romaji: "rai getsu" },
      { indonesia: "Dua bulan lagi", romaji: "sa rai getsu" },
      { indonesia: "Setiap bulan", romaji: "maitsuki" },

      // Tahun (年)
      { indonesia: "Dua tahun yang lalu", romaji: "ototoshi" },
      { indonesia: "Tahun lalu", romaji: "kyonen" },
      { indonesia: "Tahun ini", romaji: "kotoshi" },
      { indonesia: "Tahun depan", romaji: "rainen" },
      { indonesia: "Dua tahun lagi", romaji: "sarainen" },
      { indonesia: "Setiap tahun", romaji: "maitoshi / mainen" },
      { indonesia: "6 Bulan / Setengah tahun", romaji: "han toshi" },

      // Jangka Waktu - Jam (時間)
      { indonesia: "1 Jam", romaji: "ichi ji kan" },
      { indonesia: "2 Jam", romaji: "ni ji kan" },
      { indonesia: "3 Jam", romaji: "san ji kan" },
      { indonesia: "4 Jam", romaji: "yo ji kan" },
      { indonesia: "5 Jam", romaji: "go ji kan" },
      { indonesia: "6 Jam", romaji: "roku ji kan" },
      { indonesia: "7 Jam", romaji: "shichi ji kan / nana ji kan" },
      { indonesia: "8 Jam", romaji: "hachi ji kan" },
      { indonesia: "9 Jam", romaji: "ku ji kan" },
      { indonesia: "10 Jam", romaji: "juu ji kan" },
      { indonesia: "Berapa jam?", romaji: "nan ji kan" },

      // Jangka Waktu - Menit (分)
      { indonesia: "1 Menit", romaji: "ippun" },
      { indonesia: "2 Menit", romaji: "nifun" },
      { indonesia: "3 Menit", romaji: "sanpun" },
      { indonesia: "4 Menit", romaji: "yonpun" },
      { indonesia: "5 Menit", romaji: "gofun" },
      { indonesia: "6 Menit", romaji: "roppun" },
      { indonesia: "7 Menit", romaji: "nanafun" },
      { indonesia: "8 Menit", romaji: "happun" },
      { indonesia: "9 Menit", romaji: "kyuufun" },
      { indonesia: "10 Menit", romaji: "juppun / jippun" },
      { indonesia: "Berapa menit?", romaji: "nanpun" },

      // Jangka Waktu - Hari (日)
      { indonesia: "1 Hari", romaji: "ichi nichi" },
      { indonesia: "2 Hari", romaji: "futsu ka" },
      { indonesia: "3 Hari", romaji: "mik ka" },
      { indonesia: "4 Hari", romaji: "yok ka" },
      { indonesia: "5 Hari", romaji: "itsu ka" },
      { indonesia: "6 Hari", romaji: "mui ka" },
      { indonesia: "7 Hari", romaji: "nano ka" },
      { indonesia: "8 Hari", romaji: "you ka" },
      { indonesia: "9 Hari", romaji: "kokono ka" },
      { indonesia: "10 Hari", romaji: "too ka" },
      { indonesia: "Berapa hari?", romaji: "nan nichi" },

      // Jangka Waktu - Minggu (週間)
      { indonesia: "1 Minggu", romaji: "isshuukan" },
      { indonesia: "2 Minggu", romaji: "ni shuukan" },
      { indonesia: "3 Minggu", romaji: "san shuukan" },
      { indonesia: "4 Minggu", romaji: "yon shuukan" },
      { indonesia: "5 Minggu", romaji: "go shuukan" },
      { indonesia: "6 Minggu", romaji: "roku shuukan" },
      { indonesia: "7 Minggu", romaji: "nana shuukan" },
      { indonesia: "8 Minggu", romaji: "hasshuukan" },
      { indonesia: "9 Minggu", romaji: "kyuu shuukan" },
      { indonesia: "10 Minggu", romaji: "jisshuukan" },
      { indonesia: "Berapa minggu?", romaji: "nan shuukan" },

      // Jangka Waktu - Bulan (か月)
      { indonesia: "1 Bulan", romaji: "ik kagetsu" },
      { indonesia: "2 Bulan", romaji: "ni kagetsu" },
      { indonesia: "3 Bulan", romaji: "san kagetsu" },
      { indonesia: "4 Bulan", romaji: "yon kagetsu" },
      { indonesia: "5 Bulan", romaji: "go kagetsu" },
      { indonesia: "6 Bulan", romaji: "rok kagetsu / hantoshi" },
      { indonesia: "7 Bulan", romaji: "nana kagetsu" },
      { indonesia: "8 Bulan", romaji: "hak kagetsu" },
      { indonesia: "9 Bulan", romaji: "kyuu kagetsu" },
      { indonesia: "10 Bulan", romaji: "jik kagetsu" },
      { indonesia: "Berapa bulan?", romaji: "nan kagetsu" },

      // Jangka Waktu - Tahun (年間)
      { indonesia: "1 Tahun", romaji: "ichi nen" },
      { indonesia: "2 Tahun", romaji: "ni nen" },
      { indonesia: "3 Tahun", romaji: "san nen" },
      { indonesia: "4 Tahun", romaji: "yo nen" },
      { indonesia: "5 Tahun", romaji: "go nen" },
      { indonesia: "6 Tahun", romaji: "roku nen" },
      { indonesia: "7 Tahun", romaji: "nana nen / shichi nen" },
      { indonesia: "8 Tahun", romaji: "hachi nen" },
      { indonesia: "9 Tahun", romaji: "kyuu nen" },
      { indonesia: "10 Tahun", romaji: "juu nen" },
      { indonesia: "Berapa tahun?", romaji: "nan nen" }
    ],
    "penanda_waktu": [
      // Jam (時 - Ji)
      { indonesia: "Jam 1", romaji: "ichiji" },
      { indonesia: "Jam 2", romaji: "niji" },
      { indonesia: "Jam 3", romaji: "sanji" },
      { indonesia: "Jam 4", romaji: "yoji" },
      { indonesia: "Jam 5", romaji: "goji" },
      { indonesia: "Jam 6", romaji: "rokuji" },
      { indonesia: "Jam 7", romaji: "shichiji" },
      { indonesia: "Jam 8", romaji: "hachiji" },
      { indonesia: "Jam 9", romaji: "kuji" },
      { indonesia: "Jam 10", romaji: "juuji" },
      { indonesia: "Jam 11", romaji: "juuichiji" },
      { indonesia: "Jam 12", romaji: "juuniji" },
      { indonesia: "Jam berapa?", romaji: "nanji" },

      // Menit (分 - Fun/Pun)
      { indonesia: "Menit 1", romaji: "ippun" },
      { indonesia: "Menit 2", romaji: "nifun" },
      { indonesia: "Menit 3", romaji: "sanpun" },
      { indonesia: "Menit 4", romaji: "yonpun" },
      { indonesia: "Menit 5", romaji: "gofun" },
      { indonesia: "Menit 6", romaji: "roppun" },
      { indonesia: "Menit 7", romaji: "nanafun" },
      { indonesia: "Menit 8", romaji: "happun" },
      { indonesia: "Menit 9", romaji: "kyuufun" },
      { indonesia: "Menit 10", romaji: "juppun / jippun" },
      { indonesia: "Menit 15", romaji: "juugofun" },
      { indonesia: "Menit 30 / Setengah", romaji: "sanjuppun / han" },
      { indonesia: "Berapa menit?", romaji: "nanpun" },

      // Nama Hari (曜日 - Youbi)
      { indonesia: "Hari Minggu", romaji: "nichiyoubi" },
      { indonesia: "Hari Senin", romaji: "getsuyoubi" },
      { indonesia: "Hari Selasa", romaji: "kayoubi" },
      { indonesia: "Hari Rabu", romaji: "suiyoubi" },
      { indonesia: "Hari Kamis", romaji: "mokuyoubi" },
      { indonesia: "Hari Jumat", romaji: "kinyoubi" },
      { indonesia: "Hari Sabtu", romaji: "doyoubi" },
      { indonesia: "Hari apa?", romaji: "nanyoubi" },

      // Bulan (月 - Gatsu)
      { indonesia: "Januari (Bulan 1)", romaji: "ichigatsu" },
      { indonesia: "Februari (Bulan 2)", romaji: "nigatsu" },
      { indonesia: "Maret (Bulan 3)", romaji: "sangatsu" },
      { indonesia: "April (Bulan 4)", romaji: "shigatsu" },
      { indonesia: "Mei (Bulan 5)", romaji: "gogatsu" },
      { indonesia: "Juni (Bulan 6)", romaji: "rokugatsu" },
      { indonesia: "Juli (Bulan 7)", romaji: "shichigatsu" },
      { indonesia: "Agustus (Bulan 8)", romaji: "hachigatsu" },
      { indonesia: "September (Bulan 9)", romaji: "kugatsu" },
      { indonesia: "Oktober (Bulan 10)", romaji: "juugatsu" },
      { indonesia: "November (Bulan 11)", romaji: "juuichigatsu" },
      { indonesia: "Desember (Bulan 12)", romaji: "juunigatsu" },
      { indonesia: "Bulan apa?", romaji: "nangatsu" },

      // Tanggal / Hari ke-N (日 - Nichi / Tachi / Ka)
      { indonesia: "Tanggal 1", romaji: "tsuitachi" },
      { indonesia: "Tanggal 2", romaji: "futsuka" },
      { indonesia: "Tanggal 3", romaji: "mikka" },
      { indonesia: "Tanggal 4", romaji: "yokka" },
      { indonesia: "Tanggal 5", romaji: "itsuka" },
      { indonesia: "Tanggal 6", romaji: "muika" },
      { indonesia: "Tanggal 7", romaji: "nanoka" },
      { indonesia: "Tanggal 8", romaji: "youka" },
      { indonesia: "Tanggal 9", romaji: "kokonoka" },
      { indonesia: "Tanggal 10", romaji: "tooka" },
      { indonesia: "Tanggal 11", romaji: "juuichi nichi" },
      { indonesia: "Tanggal 12", romaji: "juuni nichi" },
      { indonesia: "Tanggal 13", romaji: "juusan nichi" },
      { indonesia: "Tanggal 14", romaji: "juu yokka" },
      { indonesia: "Tanggal 15", romaji: "juugo nichi" },
      { indonesia: "Tanggal 16", romaji: "juuroku nichi" },
      { indonesia: "Tanggal 17", romaji: "juushichi nichi" },
      { indonesia: "Tanggal 18", romaji: "juuhachi nichi" },
      { indonesia: "Tanggal 19", romaji: "juuku nichi" },
      { indonesia: "Tanggal 20", romaji: "hatsuka" },
      { indonesia: "Tanggal 21", romaji: "nijuuichi nichi" },
      { indonesia: "Tanggal 22", romaji: "nijuuni nichi" },
      { indonesia: "Tanggal 23", romaji: "nijuusan nichi" },
      { indonesia: "Tanggal 24", romaji: "nijuu yokka" },
      { indonesia: "Tanggal 25", romaji: "nijuugo nichi" },
      { indonesia: "Tanggal 26", romaji: "nijuuroku nichi" },
      { indonesia: "Tanggal 27", romaji: "nijuushichi nichi" },
      { indonesia: "Tanggal 28", romaji: "nijuuhachi nichi" },
      { indonesia: "Tanggal 29", romaji: "nijuuku nichi" },
      { indonesia: "Tanggal 30", romaji: "sanjuu nichi" },
      { indonesia: "Tanggal 31", romaji: "sanjuuichi nichi" },
      { indonesia: "Tanggal berapa?", romaji: "nan nichi" },

      // Keterangan Waktu Tambahan
      { indonesia: "AM (00:00 - 11:59 Pagi)", romaji: "gozen" },
      { indonesia: "PM (12:00 - 23:59 Siang/Malam)", romaji: "gogo" },
      { indonesia: "Lebih (Jam)", romaji: "tsugi" },
      { indonesia: "Kurang (Jam)", romaji: "mae" },
      { indonesia: "Tepat (Tepat Jam ...)", romaji: "choudou" }
    ],

    "kata_kerja_gol1": [
     { indonesia: "Bertemu [dengan teman]", romaji: "au" },
      { indonesia: "Bermain", romaji: "asobu" },
      { indonesia: "Mencuci", romaji: "arau" },
      { indonesia: "Ada, mempunyai", romaji: "aru" },
      { indonesia: "Ada [digunakan untuk benda mati]", romaji: "aru" },
      { indonesia: "Ada diadakan [Pesta perayaan]", romaji: "aru" },
      { indonesia: "Berjalan kaki", romaji: "aruku" },
      { indonesia: "Mengatakan, berkata", romaji: "iu" },
      { indonesia: "Pergi", romaji: "iku" },
      { indonesia: "Buru-buru", romaji: "isogu" },
      { indonesia: "Memerlukan [VISA]", romaji: "iru" },
      { indonesia: "Pindah, bergerak", romaji: "ugoku" },
      { indonesia: "Bernyanyi, menyanyi", romaji: "utau" },
      { indonesia: "Menjual", romaji: "uru" },
      { indonesia: "Meletakkan, menaruh", romaji: "oku" },
      { indonesia: "Mengirim", romaji: "okuru" },
      { indonesia: "Mengantar [Orang]", romaji: "okuru" },
      { indonesia: "Menekan", romaji: "osu" },
      { indonesia: "Teringat", romaji: "omoidasu" },
      { indonesia: "Mengira, berpikir", romaji: "omou" },
      { indonesia: "Berenang", romaji: "oyogu" },
      { indonesia: "Mengeluarkan / mengambil [Uang]", romaji: "orosu" },
      { indonesia: "Selesai", romaji: "owaru" },
      { indonesia: "Membeli", romaji: "kau" },
      { indonesia: "Mengembalikan", romaji: "kaesu" },
      { indonesia: "Pulang", romaji: "kaeru" },
      { indonesia: "Memakan, perlu", romaji: "kakaru" },
      { indonesia: "Menulis, menggambar", romaji: "kaku" },
      { indonesia: "Meminjamkan, menyewakan", romaji: "kasu" },
      { indonesia: "Menang", romaji: "katsu" },
      { indonesia: "Memakai [Topi]", romaji: "kaburu" },
      { indonesia: "Bekerja keras, Berusaha", romaji: "ganbaru" },
      { indonesia: "Mendengar", romaji: "kiku" },
      { indonesia: "Bertanya [kepada guru]", romaji: "kiku" },
      { indonesia: "Memotong, menggunting", romaji: "kiru" },
      { indonesia: "Mematikan / memadamkan", romaji: "kesu" },
      { indonesia: "Menyentuh [pintu]", romaji: "sawaru" },
      { indonesia: "Mengetahui, mengenal", romaji: "shiru" },
      { indonesia: "Menghisap [rokok], merokok", romaji: "suu" },
      { indonesia: "Tinggal", romaji: "sumu" },
      { indonesia: "Duduk", romaji: "suwaru" },
      { indonesia: "Mengeluarkan, menyerahkan, mengirim", romaji: "dasu" },
      { indonesia: "Berdiri", romaji: "tatsu" },
      { indonesia: "Memakai", romaji: "tsukau" },
      { indonesia: "Tiba, sampai", romaji: "tsuku" },
      { indonesia: "Membuat, membangun, memproduksi", romaji: "tsukuru" },
      { indonesia: "Membawa, mengajak pergi", romaji: "tsurete iku" },
      { indonesia: "Membantu", romaji: "tetsudau" },
      { indonesia: "Menginap [di hotel]", romaji: "tomaru" },
      { indonesia: "Mengambil", romaji: "toru" },
      { indonesia: "Mengambil [Foto]", romaji: "toru" },
      { indonesia: "Berumur, lanjut usia", romaji: "toru" },
      { indonesia: "Mengoreksi", romaji: "naosu" },
      { indonesia: "Kehilangan", romaji: "nakusu" },
      { indonesia: "Belajar", romaji: "narau" },
      { indonesia: "Menjadi", romaji: "naru" },
      { indonesia: "Buka [baju, sepatu dan lain-lain]", romaji: "nugu" },
      { indonesia: "Naik", romaji: "noboru" },
      { indonesia: "Minum", romaji: "nomu" },
      { indonesia: "Minum [minuman keras]", romaji: "nomu" },
      { indonesia: "Minum [obat]", romaji: "nomu" },
      { indonesia: "Naik [kereta rel listrik]", romaji: "noru" },
      { indonesia: "Masuk [ke coffee shop]", romaji: "hairu" },
      { indonesia: "Masuk [universitas]", romaji: "hairu" },
      { indonesia: "Mandi, masuk [ofuro]", romaji: "hairu" },
      { indonesia: "Memakai [sepatu, celana]", romaji: "haku" },
      { indonesia: "Bekerja", romaji: "hataraku" },
      { indonesia: "Berbicara", romaji: "hanasu" },
      { indonesia: "Membayar", romaji: "harau" },
      { indonesia: "Bermain [Bermaksud untuk bermain alat musik senar dan piano]", romaji: "hiku" },
      { indonesia: "Tarik", romaji: "hiku" },
      { indonesia: "Turun [hujan]", romaji: "furu" },
      { indonesia: "Belok [ke kanan]", romaji: "magaru" },
      { indonesia: "Menunggu", romaji: "matsu" },
      { indonesia: "Memutar", romaji: "mawasu" },
      { indonesia: "Membawa", romaji: "motsu" },
      { indonesia: "Membawa pergi", romaji: "motte iku" },
      { indonesia: "Mendapatkan, menerima", romaji: "morau" },
      { indonesia: "Berguna, bermanfaat", romaji: "yakunitatsu" },
      { indonesia: "Beristirahat, libur", romaji: "yasumu" },
      { indonesia: "Tidak masuk [kerja]", romaji: "yasumu" },
      { indonesia: "Memanggil", romaji: "yobu" },
      { indonesia: "Membaca", romaji: "yomu" },
      { indonesia: "Mengerti", romaji: "wakaru" },
      { indonesia: "Menyeberang [jembatan]", romaji: "wataru" },
      { indonesia: "Mencari", romaji: "sagasu" }
    ],

    "kata_kerja_gol2": [
      { indonesia: "Membuka", romaji: "akeru" },
      { indonesia: "Memberikan", romaji: "ageru" },
      { indonesia: "Mengumpulkan", romaji: "atsumeru" },
      { indonesia: "Mandi", romaji: "abiru" },
      { indonesia: "Ada [digunakan untuk makhluk hidup]", romaji: "iru" },
      { indonesia: "Ada [di Jepang]", romaji: "iru" },
      { indonesia: "Ada, mempunyai [anak]", romaji: "iru" },
      { indonesia: "Memasukkan", romaji: "ireru" },
      { indonesia: "Lahir", romaji: "umareru" },
      { indonesia: "Bangun", romaji: "okiru" },
      { indonesia: "Mengajar", romaji: "oshieru" },
      { indonesia: "Memberitahukan [alamat]", romaji: "oshieru" },
      { indonesia: "Mengingat, menghafal", romaji: "oboeru" },
      { indonesia: "Turun [Kereta rel listrik]", romaji: "oriru" },
      { indonesia: "Mengganti, menukar", romaji: "kaeru" },
      { indonesia: "Mengubah", romaji: "kaeru" },
      { indonesia: "Menelepon", romaji: "kakeru" },
      { indonesia: "Memakai [kaca mata]", romaji: "kakeru" },
      { indonesia: "Meminjam, menyewa", romaji: "kariru" },
      { indonesia: "Berpikir, memikirkan", romaji: "kangaeru" },
      { indonesia: "Memakai [kemeja]", romaji: "kiru" },
      { indonesia: "Berwaspada, berhati-hati", romaji: "ki wo tsukeru" },
      { indonesia: "Diberikan", romaji: "kureru" },
      { indonesia: "Menutup", romaji: "shimeru" },
      { indonesia: "Memeriksa, meneliti, mengecek", romaji: "shiraberu" },
      { indonesia: "Membuang", romaji: "suteru" },
      { indonesia: "Makan", romaji: "taberu" },
      { indonesia: "Cukup", romaji: "tariru" },
      { indonesia: "Lelah", romaji: "tsukareru" },
      { indonesia: "Menyalakan, memasang, menghidupkan", romaji: "tsukeru" },
      { indonesia: "Pergi, keluar, berangkat", romaji: "dekakeru" },
      { indonesia: "Dapat, bisa, mampu", romaji: "dekiru" },
      { indonesia: "Keluar [uang kembalian]", romaji: "deru" },
      { indonesia: "Keluar [dari coffee shop]", romaji: "deru" },
      { indonesia: "Tamat [dari universitas]", romaji: "deru" },
      { indonesia: "Menghentikan, memarkir", romaji: "tomeru" },
      { indonesia: "Tidur", romaji: "neru" },
      { indonesia: "Ganti, pindah (kereta rel)", romaji: "nori kaeru" },
      { indonesia: "Mulai", romaji: "hajimeru" },
      { indonesia: "Kalah", romaji: "makeru" },
      { indonesia: "Memperlihatkan", romaji: "miseru" },
      { indonesia: "Melihat, menonton", romaji: "miru" },
      { indonesia: "Menjemput", romaji: "mukaeru" },
      { indonesia: "Berhenti", romaji: "yameru" },
      { indonesia: "Lupa", romaji: "wasureru" },
      { indonesia: "Menyerah", romaji: "akirameru" }
    ],

    "kata_kerja_gol3": [
      { indonesia: "Mengantarkan", romaji: "annaisuru" },
      { indonesia: "Menyetir, mengendarai", romaji: "untensuru" },
      { indonesia: "Berbelanja", romaji: "kaimonosuru" },
      { indonesia: "Datang", romaji: "kuru" },
      { indonesia: "Menikah", romaji: "kekkonsuru" },
      { indonesia: "Mengunjungi", romaji: "kengakusuru" },
      { indonesia: "Meneliti", romaji: "kenkyuusuru" },
      { indonesia: "Memfoto kopi", romaji: "kopiisuru" },
      { indonesia: "Berjalan-jalan", romaji: "sanposuru" },
      { indonesia: "Melembur", romaji: "zangousuru" },
      { indonesia: "Mengerjakan, melakukan, berbuat", romaji: "suru" },
      { indonesia: "Memakai [dasi]", romaji: "suru" },
      { indonesia: "Memperbaiki", romaji: "shuurisuru" },
      { indonesia: "Dinas", romaji: "shucchousuru" },
      { indonesia: "Memperkenalkan", romaji: "shoukaisuru" },
      { indonesia: "Makan", romaji: "shokujisuru" },
      { indonesia: "Mengkhawatirkan", romaji: "shinpaisuru" },
      { indonesia: "Menjelaskan, menerangkan", romaji: "setsumeisuru" },
      { indonesia: "Mencuci pakaian", romaji: "sentakusuru" },
      { indonesia: "Membersihkan", romaji: "soujisuru" },
      { indonesia: "Membawa datang, mengajak datang", romaji: "tsuretekuru" },
      { indonesia: "Menelepon", romaji: "denwasuru" },
      { indonesia: "Belajar", romaji: "benkyousuru" },
      { indonesia: "Membawa datang", romaji: "mottekuru" },
      { indonesia: "Memesan", romaji: "yoyakusuru" },
      { indonesia: "Studi di luar negeri", romaji: "ryuugakusuru" },
      { indonesia: "Mensupport / mendukung", romaji: "oensuru" },
      { indonesia: "Lega", romaji: "anshinsuru" },
      { indonesia: "Keamanan", romaji: "anzensuru" },
      { indonesia: "Ban bocor", romaji: "pankusuru" },
      { indonesia: "Memancing", romaji: "tsurisuru" }
    ],

    // Tambahan ke dalam MASTER_HIRAGANA_LENGKAP.vocabData
"aisatsu": [
  { indonesia: "Selamat pagi", romaji: "ohayou gozaimasu" },
  { indonesia: "Selamat siang", romaji: "konnichiwa" },
  { indonesia: "Selamat malam", romaji: "konbanwa" },
  { indonesia: "Semoga cepat sembuh", romaji: "odaijini" },
  { indonesia: "Tidak apa-apa", romaji: "daijoubu" },
  { indonesia: "Apa kabar?", romaji: "ogenki desu ka?" },
  { indonesia: "Baik-baik saja", romaji: "genki desu" },
  { indonesia: "Terima kasih banyak", romaji: "arigatou gozaimasu" },
  { indonesia: "Iya, sama-sama", romaji: "douitashimashite" },
  { indonesia: "Selamat makan", romaji: "itadakimasu" },
  { indonesia: "Terima kasih hidangannya", romaji: "gochisousama deshita" },
  { indonesia: "Aku pergi dulu", romaji: "ittekimasu" },
  { indonesia: "Selamat jalan", romaji: "itterasshai" },
  { indonesia: "Aku pulang", romaji: "tadaima" },
  { indonesia: "Selamat pulang", romaji: "okaerinasai" },
  { indonesia: "Selamat tinggal", romaji: "sayounara" },
  { indonesia: "Sampai jumpa besok", romaji: "mata ashita" },
  { indonesia: "Sampai jumpa minggu depan", romaji: "mata raishuu" },
  { indonesia: "Selamat tidur", romaji: "oyasuminasai" },
  { indonesia: "Selamat datang (Restoran)", romaji: "irasshaimase" },
  { indonesia: "Selamat datang (Hotel)", romaji: "yookoso" },
  { indonesia: "Hati-hati di jalan", romaji: "kiwo tsukete kudasai" },
  { indonesia: "Ya, saya akan berhati-hati", romaji: "kiwo tsukemasu" },
  { indonesia: "Permisi / Maaf (Sopan)", romaji: "sumimasen" },
  { indonesia: "Sampai jumpa lagi", romaji: "mata" },
  { indonesia: "Lama tidak berjumpa", romaji: "hisashiburi" }
],

// Tambahkan ke dalam MASTER_HIRAGANA_LENGKAP.vocabData
"kazoku": [
  { indonesia: "Keluarga", romaji: "kazoku" },
  { indonesia: "Ayah", romaji: "chichi" },
  { indonesia: "Ibu", romaji: "haha" },
  { indonesia: "Orangtua", romaji: "ryoushin" },
  { indonesia: "Suami", romaji: "otto / shujin" },
  { indonesia: "Istri", romaji: "tsuma" },
  { indonesia: "Anak", romaji: "kodomo" },
  { indonesia: "Anak perempuan", romaji: "musume" },
  { indonesia: "Anak laki-laki", romaji: "musuko" },
  { indonesia: "Kakak perempuan", romaji: "ane" },
  { indonesia: "Kakak laki-laki", romaji: "ani" },
  { indonesia: "Adik perempuan", romaji: "imouto" },
  { indonesia: "Adik laki-laki", romaji: "otouto" },
  { indonesia: "Saudara perempuan", romaji: "shimai" },
  { indonesia: "Saudara laki-laki", romaji: "kyoudai" },
  { indonesia: "Saudara ipar", romaji: "giri no" },
  { indonesia: "Kakek", romaji: "sofu" },
  { indonesia: "Nenek", romaji: "sobo" },
  { indonesia: "Paman", romaji: "oji" },
  { indonesia: "Bibi", romaji: "oba" },
  { indonesia: "Sepupu", romaji: "itoko" },
  { indonesia: "Keponakan perempuan", romaji: "mei" },
  { indonesia: "Keponakan laki-laki", romaji: "oi" },
  { indonesia: "Anak kembar", romaji: "futago" },
  { indonesia: "Cucu", romaji: "mago" },
  { indonesia: "Bayi", romaji: "akachan" }
],

// Tambahkan ke dalam MASTER_HIRAGANA_LENGKAP.vocabData
"kata_benda": [
  { indonesia: "Hiragana", romaji: "hiragana" },
  { indonesia: "Katakana", romaji: "katakana" },
  { indonesia: "Kanji", romaji: "kanji" },
  { indonesia: "Buku", romaji: "hon" },
  { indonesia: "Buku catatan", romaji: "nooto" },
  { indonesia: "Latin", romaji: "romaji" },
  { indonesia: "Majalah", romaji: "zasshi" },
  { indonesia: "Kertas", romaji: "kami" },
  { indonesia: "Kamus", romaji: "jisho" },
  { indonesia: "Tape recorder", romaji: "tepurekoodaa" },
  { indonesia: "Telepon", romaji: "denwa" },
  { indonesia: "Radio", romaji: "rajio" },
  { indonesia: "Kamera", romaji: "kamera" },
  { indonesia: "Makanan", romaji: "tabemono" },
  { indonesia: "Minuman", romaji: "nomimono" },
  { indonesia: "Buah-buahan", romaji: "kudamono" },
  { indonesia: "Televisi", romaji: "terebi" },
  { indonesia: "Nasi", romaji: "gohan" },
  { indonesia: "Roti", romaji: "pan" },
  { indonesia: "Rumah", romaji: "uchi" },
  { indonesia: "Perusahaan", romaji: "kaisha" },
  { indonesia: "Pabrik", romaji: "koujou" },
  { indonesia: "Stasiun", romaji: "eki" },
  { indonesia: "Koran", romaji: "shinbun" },
  { indonesia: "Rumah Sakit", romaji: "byouin" },
  { indonesia: "Bank", romaji: "ginkou" },
  { indonesia: "Departemen store", romaji: "depaato" },
  { indonesia: "Toko buku", romaji: "honya" },
  { indonesia: "Kantor", romaji: "jimusho" },
  { indonesia: "Ruang kelas", romaji: "kyoushitsu" },
  { indonesia: "Kamar", romaji: "heya" },
  { indonesia: "Ruang makan", romaji: "shokudou" },
  { indonesia: "Kamar kecil", romaji: "toire / toarai" },
  { indonesia: "Loby", romaji: "robii" },
  { indonesia: "Receptionis", romaji: "uketsuke" },
  { indonesia: "Halaman", romaji: "niwa" },
  { indonesia: "Sumpit", romaji: "hashi" },
  { indonesia: "Pisau", romaji: "naifu" },
  { indonesia: "Garpu", romaji: "fooku" },
  { indonesia: "Kursi", romaji: "isu" },
  { indonesia: "Meja", romaji: "tsukue" },
  { indonesia: "Pintu", romaji: "doa" },
  { indonesia: "Jendela", romaji: "mado" },
  { indonesia: "Sendok", romaji: "supuun" },
  { indonesia: "Lampu listrik", romaji: "denki" },
  { indonesia: "Kotak", romaji: "hako" },
  { indonesia: "Pagi", romaji: "asa" },
  { indonesia: "Siang", romaji: "hiru" },
  { indonesia: "Malam", romaji: "yoru" },
  { indonesia: "Dasi", romaji: "nekutai" },
  { indonesia: "Kemeja", romaji: "shatsu" },
  { indonesia: "Rokok", romaji: "tabako" },
  { indonesia: "Asbak", romaji: "haizara" },
  { indonesia: "Pensil", romaji: "enpitsu" },
  { indonesia: "Kunci", romaji: "kagi" },
  { indonesia: "Jam", romaji: "tokei" },
  { indonesia: "Tas", romaji: "kaban" },
  { indonesia: "Pulpen", romaji: "boorupen" },
  { indonesia: "Sepatu", romaji: "kutsu" },
  { indonesia: "HP", romaji: "keitai" },
  { indonesia: "Kulkas", romaji: "reizouko" },
  { indonesia: "Bunga", romaji: "hana" },
  { indonesia: "Uang", romaji: "okane" },
  { indonesia: "Dapur", romaji: "daidokoro" },
  { indonesia: "Penghapus papan", romaji: "kokuban keshi" },
  { indonesia: "Penghapus karet", romaji: "keshi gomu" },
  { indonesia: "Air", romaji: "mizu" },
  { indonesia: "Papan tulis", romaji: "kokuban" },
  { indonesia: "Spidol/Magic marker", romaji: "majikku" },
  { indonesia: "Tembok", romaji: "kabe" },
  { indonesia: "Lantai", romaji: "yuka" },
  { indonesia: "Langit-langit", romaji: "tenjou" },
  { indonesia: "Atap", romaji: "yane" },
  { indonesia: "Sapu", romaji: "houki" },
  { indonesia: "Sampah", romaji: "gomi" },
  { indonesia: "Tempat Sampah", romaji: "gomibako" },
  { indonesia: "Sandal", romaji: "surippa" },
  { indonesia: "Kaos kaki", romaji: "kutsu shita" },
  { indonesia: "Celana pendek", romaji: "hanzu bon" },
  { indonesia: "Celana panjang", romaji: "zubon" },
  { indonesia: "Pohon", romaji: "ki" },
  { indonesia: "Api", romaji: "hi" },
  { indonesia: "Darah", romaji: "chi" },
  { indonesia: "Lalat", romaji: "hai" },
  { indonesia: "Nyamuk", romaji: "ka" },
  { indonesia: "Kantor pos", romaji: "yuubin kyoku" },
  { indonesia: "Celana dalam", romaji: "pantsu" },
  { indonesia: "Mesin ATM", romaji: "eetiiemu" },
  { indonesia: "Topi", romaji: "boushi" },
  { indonesia: "Kacamata", romaji: "megane" },
  { indonesia: "Ikat pinggang", romaji: "beruto" },
  { indonesia: "Baju", romaji: "fuku" },
  { indonesia: "Korek", romaji: "raitaa" },
  { indonesia: "Dress", romaji: "doresu" },
  { indonesia: "Dompet", romaji: "saifu" },
  { indonesia: "Helm", romaji: "herumetto" },
  { indonesia: "Sayuran", romaji: "yasai" },
  { indonesia: "Penggaris", romaji: "monosashi" },
  { indonesia: "Rautan pensil", romaji: "enpitsu kezuri" },
  { indonesia: "Kartu ATM", romaji: "kyasshu kaado" },
  { indonesia: "Ambulan", romaji: "kyuukyuusha" },
  { indonesia: "Gunting", romaji: "hasami" },
  { indonesia: "Lemari", romaji: "tana" },
  { indonesia: "AC", romaji: "eakon" },
  { indonesia: "Kipas angin", romaji: "senpuuki" },
  { indonesia: "Toko bunga", romaji: "hanaya" },
  { indonesia: "Sepeda", romaji: "jitensha" },
  { indonesia: "Patung/Gajah", romaji: "zou" },
  { indonesia: "Motor", romaji: "ootobaiku" },
  { indonesia: "Kasur", romaji: "beddo" },
  { indonesia: "Bantal", romaji: "makura" },
  { indonesia: "Selimut", romaji: "buranketto" },
  { indonesia: "Boneka", romaji: "ningyou" },
  { indonesia: "Perpustakaan", romaji: "toshokan" },
  { indonesia: "Cermin", romaji: "kagami" },
  { indonesia: "Cincin", romaji: "yubiwa" },
  { indonesia: "Kota", romaji: "machi" },
  { indonesia: "Tanah", romaji: "tsuchi" },
  { indonesia: "Ranting", romaji: "eda" },
  { indonesia: "Jam tangan", romaji: "udedokei" },
  { indonesia: "Kereta api", romaji: "densha" },
  { indonesia: "Kereta bawah tanah", romaji: "chikatetsu" },
  { indonesia: "Kereta cepat", romaji: "shinkansen" },
  { indonesia: "Pesawat", romaji: "hikouki" },
  { indonesia: "Mobil", romaji: "kuruma" },
  { indonesia: "Bus", romaji: "basu" },
  { indonesia: "Karet", romaji: "gomu" },
  { indonesia: "Bandara", romaji: "kuukou" },
  { indonesia: "Peta", romaji: "chizu" },
  { indonesia: "Toko", romaji: "mise" },
  { indonesia: "Pin ATM", romaji: "anshou bangou" },
  { indonesia: "Kotak pensil", romaji: "fudebako" },
  { indonesia: "Kedai kopi", romaji: "kissaten" },
  { indonesia: "Perempatan", romaji: "kousaten" },
  { indonesia: "Gunung", romaji: "yama" },
  { indonesia: "Sungai", romaji: "kawa" },
  { indonesia: "Danau", romaji: "mizuumi" },
  { indonesia: "Pantai", romaji: "umi" },
  { indonesia: "Ladang/Kebun", romaji: "hatake" },
  { indonesia: "Tempat kerja", romaji: "shokuba" },
  { indonesia: "Alat", romaji: "dougu" },
  { indonesia: "Sepatu kerja", romaji: "anzenkutsu" },
  { indonesia: "Sepatu boot", romaji: "nagakutsu" },
  { indonesia: "Ban", romaji: "taiya" },
  { indonesia: "Sarung tangan", romaji: "tebukuro" },
  { indonesia: "Masker", romaji: "masuku" },
  { indonesia: "Ikan", romaji: "sakana" },
  { indonesia: "Tempat parkir", romaji: "chuushajou" },
  { indonesia: "Alat pel", romaji: "moppu" },
  { indonesia: "Piring", romaji: "sara" },
  { indonesia: "Sekolah", romaji: "gakkou" },
  { indonesia: "Kartu nama", romaji: "meishi" },
  { indonesia: "Perhiasan", romaji: "akusesarii" },
  { indonesia: "Pegawai stasiun", romaji: "ekiin" },
  { indonesia: "Payung", romaji: "kasa" },
  { indonesia: "Kartu", romaji: "kaado" },
  { indonesia: "Tempat penjualan", romaji: "uriba" },
  { indonesia: "Toko sepatu", romaji: "kutsuya" },
  { indonesia: "Gedung kesenian", romaji: "bijutsukan" },
  { indonesia: "Oleh-oleh", romaji: "omiyage" },
  { indonesia: "Buku agenda", romaji: "techou" }
]
  }
};